/**
 * List and detector for nouns representing humans, professions, roles, and family members
 * ("Personen- und Berufsbezeichnungen").
 *
 * For these nouns, grammatical gender is directly derived from natural gender
 * (e.g. der Arzt, der Patient, der Bettler, der Fahrer, die Lehrerin), which makes
 * guessing their gender trivial and less useful for learners practicing abstract gender.
 */

export const PEOPLE_AND_PROFESSIONS_SET = new Set<string>([
  // Professions, occupations, titles & roles
  'Akteur',
  'Amerikaner',
  'Anwalt',
  'Arbeiter',
  'Arzt',
  'Ärztin',
  'Autor',
  'Autorin',
  'Außenminister',
  'Beamter',
  'Beamtin',
  'Benutzer',
  'Berater',
  'Besitzer',
  'Besucher',
  'Bettler',
  'Bürgermeister',
  'Champion',
  'Chef',
  'Chefin',
  'Dichter',
  'Direktor',
  'Doktor',
  'Eigentümer',
  'Einwohner',
  'Engländer',
  'Erwachsener',
  'Experte',
  'Fahrer',
  'Finanzminister',
  'Forscher',
  'Fotograf',
  'Führer',
  'Geschäftsführer',
  'Innenminister',
  'Journalist',
  'Jugendlicher',
  'Jurist',
  'Jäger',
  'Kaiser',
  'Kanzler',
  'Kapitän',
  'Kaufmann',
  'Käufer',
  'Kellner',
  'Koch',
  'Kollege',
  'Kollegin',
  'Kunde',
  'Kundin',
  'König',
  'Königin',
  'Künstler',
  'Künstlerin',
  'Lehrer',
  'Lehrerin',
  'Leiter',
  'Leser',
  'Manager',
  'Meister',
  'Militärangehöriger',
  'Minister',
  'Ministerpräsident',
  'Mitarbeiter',
  'Musiker',
  'Nutzer',
  'Offizier',
  'Palästinenser',
  'Partner',
  'Patient',
  'Pfarrer',
  'Pilot',
  'Politiker',
  'Polizist',
  'Priester',
  'Professor',
  'Rechtsanwalt',
  'Regisseur',
  'Richter',
  'Russe',
  'Schauspieler',
  'Schauspielerin',
  'Schriftsteller',
  'Schüler',
  'Schülerin',
  'Sieger',
  'Soldat',
  'Spezialist',
  'Spieler',
  'Sportler',
  'Student',
  'Studentin',
  'Sänger',
  'Teilnehmer',
  'Trainer',
  'Täter',
  'Unternehmer',
  'Verbraucher',
  'Verkäufer',
  'Verlierer',
  'Vertreter',
  'Weltmeister',
  'Wissenschaftler',
  'Zuhörer',
  'Zuschauer',

  // Humans, relationships & family
  'Baby',
  'Bruder',
  'Bube',
  'Bürger',
  'Dame',
  'Eltern',
  'Familie',
  'Feind',
  'Frau',
  'Freund',
  'Freundin',
  'Fräulein',
  'Gast',
  'Gegner',
  'Großmutter',
  'Großvater',
  'Held',
  'Herr',
  'Junge',
  'Kind',
  'Leute',
  'Mann',
  'Mensch',
  'Mitglied',
  'Mutter',
  'Mädchen',
  'Nachbar',
  'Nachbarin',
  'Onkel',
  'Opfer',
  'Person',
  'Schwester',
  'Sohn',
  'Tante',
  'Tochter',
  'Vater',
  'Zeuge'
]);

export function isPersonOrProfession(baseNoun: string): boolean {
  if (!baseNoun) return false;
  if (PEOPLE_AND_PROFESSIONS_SET.has(baseNoun)) return true;

  // Suffix checks for German profession/female forms:
  // e.g. *ärztin, *lehrerin, *spielerin, *meisterin
  if (baseNoun.endsWith('in') && PEOPLE_AND_PROFESSIONS_SET.has(baseNoun.slice(0, -2))) {
    return true;
  }
  return false;
}
